name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - run: ./mvnw clean install -DskipTests

    - name: Run SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=spring-petclinic \
          -Dsonar.sources=src \
          -Dsonar.host.url=http://34.93.127.207:9000 \
          -Dsonar.login=$SONAR_TOKEN

    - name: Check Quality Gate
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sleep 30
        STATUS=$(curl -s -u $SONAR_TOKEN: http://34.93.127.207:9000/api/qualitygates/project_status?projectKey=spring-petclinic | jq -r '.projectStatus.status')
        if [ "$STATUS" != "OK" ]; then
          echo "Quality Gate failed!"
          exit 1
        fi
