name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build the project
      run: ./mvnw clean verify -DskipTests

    - name: Run SonarQube Scan with Maven
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        ./mvnw sonar:sonar \
          -Dsonar.projectKey=spring-petclinic \
          -Dsonar.host.url=http://34.93.127.207:9000 \
          -Dsonar.login=$SONAR_TOKEN

    - name: Check Quality Gate Status
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        echo "Waiting for SonarQube analysis to be available..."
        sleep 30
        STATUS=$(curl -s -u $SONAR_TOKEN: http://34.93.127.207:9000/api/qualitygates/project_status?projectKey=spring-petclinic | jq -r '.projectStatus.status')
        echo "Quality Gate Status: $STATUS"
        if [ "$STATUS" != "OK" ]; then
          echo "Quality Gate failed!"
          exit 1
        else
          echo "Quality Gate passed!"
        fi
